"""
Sparkle starter question bank -- 2 questions per concept across DSA, Python,
SQL, and Machine Learning (78 questions total).

This is an initial bank to get the dynamic quiz engine fully working end
to end. The product spec targets ~280 questions (100 DSA / 60 Python /
60 SQL / 60 ML) -- expanding this list is a pure content task: append more
dicts in the same shape and re-run `python -m app.db.seed`, no application
code changes needed.
"""

QUESTIONS = [
    # ================= DSA =================
    {"concept_slug": "arrays", "text": "What is the time complexity of accessing an element by index in an array?",
     "options": {"A": "O(1)", "B": "O(n)", "C": "O(log n)", "D": "O(n^2)"}, "correct_option": "A",
     "difficulty": 1, "explanation": "Arrays support direct indexed access via a memory offset, so it's O(1)."},
    {"concept_slug": "arrays", "text": "What is the time complexity of inserting an element at the beginning of an array of size n?",
     "options": {"A": "O(1)", "B": "O(n)", "C": "O(log n)", "D": "O(n^2)"}, "correct_option": "B",
     "difficulty": 2, "explanation": "All existing elements must shift right by one position, which takes O(n)."},

    {"concept_slug": "strings", "text": "In Python, strings are:", "options": {"A": "Mutable", "B": "Immutable", "C": "Mutable only inside functions", "D": "Mutable only if declared with var"},
     "correct_option": "B", "difficulty": 1, "explanation": "Python strings cannot be changed in place; any 'modification' creates a new string object."},
    {"concept_slug": "strings", "text": "What is the time complexity of concatenating two strings of length n and m?",
     "options": {"A": "O(1)", "B": "O(min(n,m))", "C": "O(n + m)", "D": "O(n * m)"}, "correct_option": "C",
     "difficulty": 2, "explanation": "A new string of length n+m must be built, copying every character from both inputs."},

    {"concept_slug": "hashing", "text": "What is the average time complexity of a lookup in a hash map?",
     "options": {"A": "O(1)", "B": "O(n)", "C": "O(log n)", "D": "O(n log n)"}, "correct_option": "A",
     "difficulty": 1, "explanation": "With a good hash function and low load factor, lookups are O(1) on average."},
    {"concept_slug": "hashing", "text": "A hash collision occurs when:",
     "options": {"A": "Two different keys map to the same bucket", "B": "A key maps to a negative index", "C": "The hash map is empty", "D": "A key is deleted"},
     "correct_option": "A", "difficulty": 2, "explanation": "Collisions happen when the hash function maps distinct keys to the same slot, requiring a resolution strategy like chaining."},

    {"concept_slug": "two-pointers", "text": "The classic two-pointer approach for finding a pair with a given sum works most efficiently when the array is:",
     "options": {"A": "Sorted", "B": "Reversed", "C": "Unsorted", "D": "Containing duplicates only"},
     "correct_option": "A", "difficulty": 2, "explanation": "Sorting lets you move the low/high pointers inward based on comparing the current sum to the target."},
    {"concept_slug": "two-pointers", "text": "Two pointers moving toward each other from opposite ends of an array is typically used to:",
     "options": {"A": "Sort the array", "B": "Find pairs or reverse a sequence in O(n)", "C": "Build a hash map", "D": "Traverse a tree"},
     "correct_option": "B", "difficulty": 2, "explanation": "This pattern avoids nested loops for problems like pair-sum or in-place reversal."},

    {"concept_slug": "sliding-window", "text": "The sliding window technique is most useful for problems involving:",
     "options": {"A": "Random access to any index", "B": "Contiguous subarrays or substrings", "C": "Sorting a linked list", "D": "Graph traversal"},
     "correct_option": "B", "difficulty": 2, "explanation": "Sliding window maintains a running range over a contiguous sequence, updating it incrementally instead of recomputing from scratch."},
    {"concept_slug": "sliding-window", "text": "In a variable-size sliding window, you shrink the window from the left when:",
     "options": {"A": "The window is empty", "B": "The current window violates the problem's constraint", "C": "You reach the end of the array", "D": "Never -- windows only grow"},
     "correct_option": "B", "difficulty": 3, "explanation": "Shrinking restores the constraint (e.g. sum too large, too many distinct characters) while keeping the window as large as valid."},

    {"concept_slug": "stack", "text": "A stack follows which ordering principle?",
     "options": {"A": "FIFO", "B": "LIFO", "C": "Random access", "D": "Priority-based"}, "correct_option": "B",
     "difficulty": 1, "explanation": "Stack = Last In, First Out -- the most recently pushed element is popped first."},
    {"concept_slug": "stack", "text": "Which data structure is most natural for checking balanced parentheses in an expression?",
     "options": {"A": "Queue", "B": "Stack", "C": "Hash map", "D": "Linked list"}, "correct_option": "B",
     "difficulty": 2, "explanation": "Pushing opening brackets and popping on matching closing brackets naturally verifies nesting/order."},

    {"concept_slug": "queue", "text": "A queue follows which ordering principle?",
     "options": {"A": "LIFO", "B": "FIFO", "C": "Random", "D": "Priority-based only"}, "correct_option": "B",
     "difficulty": 1, "explanation": "Queue = First In, First Out -- elements are processed in the order they arrived."},
    {"concept_slug": "queue", "text": "Breadth-first search (BFS) on a graph relies on which data structure?",
     "options": {"A": "Stack", "B": "Queue", "C": "Heap only", "D": "Binary search tree"}, "correct_option": "B",
     "difficulty": 2, "explanation": "BFS explores level by level, using a queue to process nodes in the order they were discovered."},

    {"concept_slug": "linked-list", "text": "What is the time complexity of inserting at the head of a singly linked list?",
     "options": {"A": "O(1)", "B": "O(n)", "C": "O(log n)", "D": "O(n^2)"}, "correct_option": "A",
     "difficulty": 1, "explanation": "You just create a new node and point it at the old head -- no traversal needed."},
    {"concept_slug": "linked-list", "text": "Detecting a cycle in a linked list in O(1) space is typically done using:",
     "options": {"A": "A hash set of visited nodes", "B": "Floyd's slow/fast pointer technique", "C": "Sorting the list", "D": "Recursion with memoization"},
     "correct_option": "B", "difficulty": 3, "explanation": "A slow pointer (1 step) and fast pointer (2 steps) will eventually meet if there's a cycle, using only O(1) extra space."},

    {"concept_slug": "trees", "text": "In a binary search tree, for any given node, the left subtree contains values that are:",
     "options": {"A": "Greater than the node", "B": "Less than the node", "C": "Equal to the node", "D": "Unrelated to the node"},
     "correct_option": "B", "difficulty": 2, "explanation": "BST invariant: left subtree < node < right subtree, at every node."},
    {"concept_slug": "trees", "text": "Which traversal of a binary search tree visits nodes in sorted order?",
     "options": {"A": "Pre-order", "B": "Post-order", "C": "In-order", "D": "Level-order"}, "correct_option": "C",
     "difficulty": 2, "explanation": "In-order (left, node, right) visits BST nodes in ascending sorted order."},

    {"concept_slug": "graphs", "text": "Which algorithm finds the shortest path between two nodes in an unweighted graph?",
     "options": {"A": "DFS", "B": "BFS", "C": "Dynamic programming", "D": "Binary search"}, "correct_option": "B",
     "difficulty": 3, "explanation": "BFS explores nodes level by level, guaranteeing the first time you reach a node is via a shortest path (in hops)."},
    {"concept_slug": "graphs", "text": "Depth-first search (DFS), whether recursive or iterative, conceptually relies on which structure?",
     "options": {"A": "Queue", "B": "Stack", "C": "Priority queue", "D": "Hash map"}, "correct_option": "B",
     "difficulty": 2, "explanation": "DFS goes as deep as possible before backtracking -- recursion's call stack (or an explicit stack) provides exactly that behavior."},

    {"concept_slug": "dynamic-programming", "text": "Dynamic programming is applicable when a problem exhibits:",
     "options": {"A": "Random substructure", "B": "Overlapping subproblems and optimal substructure", "C": "No repeated subproblems", "D": "Only greedy choices"},
     "correct_option": "B", "difficulty": 3, "explanation": "DP pays off specifically because subproblems repeat and an optimal solution can be built from optimal subsolutions."},
    {"concept_slug": "dynamic-programming", "text": "Storing the results of subproblems to avoid recomputing them is called:",
     "options": {"A": "Memoization", "B": "Normalization", "C": "Serialization", "D": "Indexing"}, "correct_option": "A",
     "difficulty": 2, "explanation": "Memoization caches subproblem results (top-down); tabulation is the equivalent bottom-up approach."},

    # ================= Python =================
    {"concept_slug": "py-syntax", "text": "Which of the following is a valid Python variable name?",
     "options": {"A": "2var", "B": "my-var", "C": "my_var", "D": "class"}, "correct_option": "C",
     "difficulty": 1, "explanation": "Identifiers can't start with a digit, can't contain hyphens, and can't be reserved keywords like 'class'."},
    {"concept_slug": "py-syntax", "text": "Python uses which mechanism to define code blocks (instead of braces)?",
     "options": {"A": "Semicolons", "B": "Indentation", "C": "Parentheses", "D": "Tabs are forbidden entirely"},
     "correct_option": "B", "difficulty": 1, "explanation": "Python is whitespace-sensitive -- consistent indentation defines block structure."},

    {"concept_slug": "py-functions", "text": "What is a well-known gotcha with using a mutable default argument (like a list) in a Python function?",
     "options": {"A": "It causes a syntax error", "B": "It's shared across all calls to that function", "C": "It gets deleted after first call", "D": "It becomes immutable automatically"},
     "correct_option": "B", "difficulty": 3, "explanation": "Default arguments are evaluated once at function definition time, so a mutable default persists and accumulates state across calls."},
    {"concept_slug": "py-functions", "text": "In a function signature, `*args` collects extra positional arguments into a:",
     "options": {"A": "Dictionary", "B": "Set", "C": "Tuple", "D": "String"}, "correct_option": "C",
     "difficulty": 2, "explanation": "`*args` gathers any extra positional arguments as a tuple inside the function."},

    {"concept_slug": "py-oop", "text": "Does Python support multiple inheritance?",
     "options": {"A": "No, never", "B": "Yes", "C": "Only with special libraries", "D": "Only for abstract classes"},
     "correct_option": "B", "difficulty": 2, "explanation": "A Python class can inherit from multiple base classes; method resolution order (MRO) determines lookup order."},
    {"concept_slug": "py-oop", "text": "The `__init__` method in a Python class is:",
     "options": {"A": "Called automatically when an instance is created", "B": "Optional and never called automatically", "C": "Only used for static methods", "D": "The destructor"},
     "correct_option": "A", "difficulty": 1, "explanation": "`__init__` is the initializer, invoked right after a new instance is created via the class."},

    {"concept_slug": "py-file-handling", "text": "The preferred way to open a file safely in Python (ensuring it's closed) is:",
     "options": {"A": "open() without closing", "B": "A `with` statement", "C": "A global file handle", "D": "try/except with no finally"},
     "correct_option": "B", "difficulty": 1, "explanation": "`with open(...) as f:` is a context manager that guarantees the file is closed even if an exception occurs."},
    {"concept_slug": "py-file-handling", "text": "Which file mode opens a file for appending (writing at the end without truncating)?",
     "options": {"A": "'r'", "B": "'w'", "C": "'a'", "D": "'x'"}, "correct_option": "C",
     "difficulty": 1, "explanation": "'a' opens for append, preserving existing content and writing new data at the end."},

    {"concept_slug": "py-exceptions", "text": "A `finally` block in Python executes:",
     "options": {"A": "Only if an exception occurred", "B": "Only if no exception occurred", "C": "Whether or not an exception occurred", "D": "Never, if there's a return in try"},
     "correct_option": "C", "difficulty": 2, "explanation": "`finally` always runs -- it's meant for cleanup that must happen regardless of success or failure."},
    {"concept_slug": "py-exceptions", "text": "Which keyword lets you deliberately trigger an exception in Python?",
     "options": {"A": "throw", "B": "raise", "C": "except", "D": "catch"}, "correct_option": "B",
     "difficulty": 1, "explanation": "Python uses `raise SomeException(...)` to trigger an exception (not `throw`, unlike some other languages)."},

    {"concept_slug": "py-modules", "text": "The purpose of `if __name__ == \"__main__\":` in a Python file is to:",
     "options": {"A": "Import the module faster", "B": "Run code only when the file is executed directly, not when imported", "C": "Define the main class", "D": "Required syntax for every file"},
     "correct_option": "B", "difficulty": 2, "explanation": "`__name__` is `\"__main__\"` only when the script is run directly, letting you separate script behavior from importable module behavior."},
    {"concept_slug": "py-modules", "text": "Which tool is used to install third-party Python packages?",
     "options": {"A": "npm", "B": "pip", "C": "cargo", "D": "make"}, "correct_option": "B",
     "difficulty": 1, "explanation": "pip is Python's standard package installer, pulling from PyPI by default."},

    {"concept_slug": "py-stdlib", "text": "Which standard library module provides `Counter` and `defaultdict`?",
     "options": {"A": "itertools", "B": "collections", "C": "functools", "D": "typing"}, "correct_option": "B",
     "difficulty": 2, "explanation": "The `collections` module provides specialized container datatypes including Counter and defaultdict."},
    {"concept_slug": "py-stdlib", "text": "Which standard library module provides `reduce` and `lru_cache`?",
     "options": {"A": "functools", "B": "collections", "C": "itertools", "D": "os"}, "correct_option": "A",
     "difficulty": 3, "explanation": "`functools` provides higher-order function tools like `reduce`, `lru_cache`, and `partial`."},

    {"concept_slug": "py-problem-solving", "text": "What does `[x*x for x in range(4)]` evaluate to?",
     "options": {"A": "[0, 1, 4, 9]", "B": "[1, 4, 9, 16]", "C": "[0, 1, 2, 3]", "D": "[4]"}, "correct_option": "A",
     "difficulty": 2, "explanation": "range(4) yields 0,1,2,3; squaring each gives [0, 1, 4, 9]."},
    {"concept_slug": "py-problem-solving", "text": "For building a large string from many pieces, which is generally more efficient?",
     "options": {"A": "Repeated += concatenation in a loop", "B": "''.join(list_of_pieces)", "C": "Both are identical in performance", "D": "Using a dictionary"},
     "correct_option": "B", "difficulty": 3, "explanation": "Since strings are immutable, repeated += creates many intermediate copies; `join` builds the result in one pass."},

    # ================= SQL =================
    {"concept_slug": "sql-select", "text": "Which symbol selects all columns from a table in SQL?",
     "options": {"A": "%", "B": "*", "C": "#", "D": "ALL"}, "correct_option": "B",
     "difficulty": 1, "explanation": "`SELECT * FROM table` returns every column."},
    {"concept_slug": "sql-select", "text": "To give a column a different name in the query's output, you use:",
     "options": {"A": "RENAME", "B": "AS (alias)", "C": "LABEL", "D": "CAST"}, "correct_option": "B",
     "difficulty": 1, "explanation": "`SELECT col AS alias_name` renames the column in the result set only."},

    {"concept_slug": "sql-where", "text": "The WHERE clause filters:",
     "options": {"A": "Groups, after aggregation", "B": "Individual rows, before grouping", "C": "Column names", "D": "Only numeric columns"},
     "correct_option": "B", "difficulty": 1, "explanation": "WHERE filters rows before any GROUP BY aggregation happens."},
    {"concept_slug": "sql-where", "text": "Which operator checks if a value matches any value in a given list?",
     "options": {"A": "IN", "B": "LIKE", "C": "BETWEEN", "D": "EXISTS"}, "correct_option": "A",
     "difficulty": 2, "explanation": "`WHERE col IN (v1, v2, v3)` matches any of the listed values."},

    {"concept_slug": "sql-group-by", "text": "GROUP BY is used to:",
     "options": {"A": "Sort rows", "B": "Aggregate rows that share the same value(s) in specified columns", "C": "Remove duplicate columns", "D": "Join two tables"},
     "correct_option": "B", "difficulty": 2, "explanation": "GROUP BY collapses rows sharing grouping-column values so aggregate functions can be applied per group."},
    {"concept_slug": "sql-group-by", "text": "To filter groups AFTER aggregation (e.g. only groups with COUNT > 5), you use:",
     "options": {"A": "WHERE", "B": "HAVING", "C": "FILTER", "D": "ORDER BY"}, "correct_option": "B",
     "difficulty": 3, "explanation": "WHERE can't reference aggregate results because it runs before grouping; HAVING filters after aggregation."},

    {"concept_slug": "sql-order-by", "text": "By default, ORDER BY sorts results in which order?",
     "options": {"A": "Descending", "B": "Ascending", "C": "Random", "D": "Insertion order"}, "correct_option": "B",
     "difficulty": 1, "explanation": "ASC is the default; you must explicitly add DESC for descending order."},
    {"concept_slug": "sql-order-by", "text": "To sort a query's results in descending order, you add:",
     "options": {"A": "DESC", "B": "REVERSE", "C": "DOWN", "D": "MAX"}, "correct_option": "A",
     "difficulty": 1, "explanation": "`ORDER BY column DESC` sorts from highest to lowest."},

    {"concept_slug": "sql-joins", "text": "Which join returns only rows that have matches in both tables?",
     "options": {"A": "LEFT JOIN", "B": "RIGHT JOIN", "C": "INNER JOIN", "D": "FULL OUTER JOIN"}, "correct_option": "C",
     "difficulty": 2, "explanation": "INNER JOIN returns only rows where the join condition matches in both tables."},
    {"concept_slug": "sql-joins", "text": "Which join returns all rows from the left table, plus matched rows from the right (with NULLs where there's no match)?",
     "options": {"A": "INNER JOIN", "B": "LEFT JOIN", "C": "CROSS JOIN", "D": "SELF JOIN"}, "correct_option": "B",
     "difficulty": 2, "explanation": "LEFT JOIN keeps every row from the left table regardless of a match, filling unmatched right-side columns with NULL."},

    {"concept_slug": "sql-subqueries", "text": "A subquery that references a column from its outer query is called:",
     "options": {"A": "A correlated subquery", "B": "A CTE", "C": "A window function", "D": "A trigger"}, "correct_option": "A",
     "difficulty": 4, "explanation": "Correlated subqueries re-execute once per outer row because they depend on that row's values."},
    {"concept_slug": "sql-subqueries", "text": "Subqueries in SQL can appear in which clauses?",
     "options": {"A": "Only WHERE", "B": "Only SELECT", "C": "SELECT, WHERE, and FROM", "D": "Only FROM"},
     "correct_option": "C", "difficulty": 3, "explanation": "Subqueries are flexible -- they can produce a scalar value in SELECT, a filter set in WHERE, or a derived table in FROM."},

    {"concept_slug": "sql-aggregations", "text": "Which function returns the number of rows matching a query?",
     "options": {"A": "SUM", "B": "COUNT", "C": "AVG", "D": "TOTAL"}, "correct_option": "B",
     "difficulty": 1, "explanation": "COUNT(*) or COUNT(column) tallies rows."},
    {"concept_slug": "sql-aggregations", "text": "By default, does AVG() include NULL values from the column in its calculation?",
     "options": {"A": "Yes, NULLs count as 0", "B": "No, NULLs are ignored", "C": "It throws an error", "D": "Only in Postgres"},
     "correct_option": "B", "difficulty": 3, "explanation": "Aggregate functions like AVG, SUM, COUNT(column) skip NULL values rather than treating them as zero."},

    {"concept_slug": "sql-window-functions", "text": "`ROW_NUMBER()` assigns:",
     "options": {"A": "The same number to tied rows", "B": "A unique sequential integer to each row within a partition", "C": "A random number", "D": "The count of all rows"},
     "correct_option": "B", "difficulty": 4, "explanation": "ROW_NUMBER() always gives distinct sequential numbers, unlike RANK()/DENSE_RANK() which can tie."},
    {"concept_slug": "sql-window-functions", "text": "How do window functions fundamentally differ from GROUP BY aggregation?",
     "options": {"A": "They can't use aggregate functions at all", "B": "They don't collapse rows into a single output row per group", "C": "They only work on one column", "D": "There is no real difference"},
     "correct_option": "B", "difficulty": 4, "explanation": "Window functions compute aggregates 'over' a partition while still returning one row per original input row."},

    {"concept_slug": "sql-normalization", "text": "First normal form (1NF) requires that:",
     "options": {"A": "Every table has a foreign key", "B": "Column values are atomic (indivisible)", "C": "There are no NULLs anywhere", "D": "Tables have at least 3 columns"},
     "correct_option": "B", "difficulty": 3, "explanation": "1NF disallows repeating groups or multi-valued fields -- each column must hold a single, indivisible value."},
    {"concept_slug": "sql-normalization", "text": "The primary goal of database normalization is to:",
     "options": {"A": "Speed up all queries automatically", "B": "Reduce data redundancy and avoid update anomalies", "C": "Remove the need for primary keys", "D": "Make schemas smaller in file size only"},
     "correct_option": "B", "difficulty": 3, "explanation": "Normalization organizes data to minimize duplication and the inconsistencies that duplication can cause on updates."},

    {"concept_slug": "sql-indexing", "text": "An index primarily speeds up:",
     "options": {"A": "INSERT statements", "B": "Read/lookup queries", "C": "DELETE statements only", "D": "Nothing measurable"},
     "correct_option": "B", "difficulty": 3, "explanation": "Indexes create an ordered lookup structure (often a B-tree) that dramatically speeds up reads matching the indexed column(s)."},
    {"concept_slug": "sql-indexing", "text": "A downside of adding many indexes to a table is:",
     "options": {"A": "SELECT queries become slower", "B": "Writes (INSERT/UPDATE/DELETE) become slower", "C": "The table can no longer be queried", "D": "There is no downside"},
     "correct_option": "B", "difficulty": 4, "explanation": "Every index must be updated on writes, so more indexes mean more write overhead even though reads get faster."},

    # ================= Machine Learning =================
    {"concept_slug": "ml-linear-regression", "text": "Linear regression is used to predict:",
     "options": {"A": "A discrete category", "B": "A continuous numeric value", "C": "A ranking only", "D": "Cluster membership"},
     "correct_option": "B", "difficulty": 1, "explanation": "Linear regression fits a continuous linear relationship between inputs and a numeric target."},
    {"concept_slug": "ml-linear-regression", "text": "Which cost function is most commonly minimized in ordinary linear regression?",
     "options": {"A": "Cross-entropy loss", "B": "Mean Squared Error", "C": "Hinge loss", "D": "KL divergence"},
     "correct_option": "B", "difficulty": 2, "explanation": "MSE penalizes squared differences between predicted and actual values, and has a convenient closed-form/gradient solution for linear models."},

    {"concept_slug": "ml-logistic-regression", "text": "Despite its name, logistic regression is actually used for:",
     "options": {"A": "Regression (continuous output)", "B": "Classification", "C": "Clustering", "D": "Dimensionality reduction"},
     "correct_option": "B", "difficulty": 2, "explanation": "Logistic regression models the probability of a class using a linear model passed through a sigmoid, making it a classifier."},
    {"concept_slug": "ml-logistic-regression", "text": "Logistic regression maps its linear output to a [0,1] probability using which function?",
     "options": {"A": "ReLU", "B": "Sigmoid", "C": "Softmax only", "D": "Identity"}, "correct_option": "B",
     "difficulty": 2, "explanation": "The sigmoid function squashes any real number into the (0,1) range, interpretable as a probability."},

    {"concept_slug": "ml-regression", "text": "Which metric is commonly used to evaluate how well a regression model fits the data?",
     "options": {"A": "Accuracy", "B": "R-squared", "C": "Precision", "D": "F1 score"}, "correct_option": "B",
     "difficulty": 2, "explanation": "R-squared measures the proportion of variance in the target explained by the model -- a standard regression fit metric."},
    {"concept_slug": "ml-regression", "text": "Ridge regression differs from ordinary linear regression by adding:",
     "options": {"A": "An L2 penalty on the coefficients", "B": "More training data automatically", "C": "A decision tree component", "D": "A softmax output layer"},
     "correct_option": "A", "difficulty": 4, "explanation": "Ridge regression adds an L2 (squared-magnitude) penalty on coefficients to shrink them and reduce overfitting."},

    {"concept_slug": "ml-classification", "text": "A confusion matrix is used to evaluate:",
     "options": {"A": "Regression models", "B": "Classification models", "C": "Clustering only", "D": "Feature scaling"},
     "correct_option": "B", "difficulty": 2, "explanation": "A confusion matrix breaks down predicted vs. actual classes (true/false positives/negatives), which only makes sense for classification."},
    {"concept_slug": "ml-classification", "text": "Which of the following is NOT typically considered a classification algorithm?",
     "options": {"A": "Logistic Regression", "B": "Decision Tree", "C": "Linear Regression", "D": "k-Nearest Neighbors"},
     "correct_option": "C", "difficulty": 3, "explanation": "Linear regression predicts continuous values; the others (as typically used) predict discrete class labels."},

    {"concept_slug": "ml-model-evaluation", "text": "Splitting data into train/validation/test sets primarily helps you:",
     "options": {"A": "Train the model faster", "B": "Get an unbiased estimate of how the model generalizes", "C": "Avoid needing any preprocessing", "D": "Increase the size of the dataset"},
     "correct_option": "B", "difficulty": 2, "explanation": "Evaluating on held-out data (not used for training) estimates real-world performance rather than memorization."},
    {"concept_slug": "ml-model-evaluation", "text": "k-fold cross-validation helps by:",
     "options": {"A": "Using multiple train/test splits to get a more robust performance estimate", "B": "Training k separate unrelated models for production", "C": "Eliminating the need for a test set entirely", "D": "Only working for regression problems"},
     "correct_option": "A", "difficulty": 3, "explanation": "Averaging performance across k different splits reduces the variance of a single train/test split's estimate."},

    {"concept_slug": "ml-precision-recall", "text": "Precision measures:",
     "options": {"A": "Of all actual positives, how many were correctly predicted", "B": "Of all predicted positives, how many were actually positive", "C": "Overall correctness across all classes", "D": "The speed of the model"},
     "correct_option": "B", "difficulty": 3, "explanation": "Precision = TP / (TP + FP) -- how trustworthy a positive prediction is."},
    {"concept_slug": "ml-precision-recall", "text": "Recall measures:",
     "options": {"A": "Of all predicted positives, how many were actually positive", "B": "Of all actual positives, how many were correctly identified", "C": "Model training time", "D": "The number of features used"},
     "correct_option": "B", "difficulty": 3, "explanation": "Recall = TP / (TP + FN) -- how many of the real positive cases the model actually caught."},

    {"concept_slug": "ml-preprocessing", "text": "Scaling features to a similar range is especially important for algorithms like:",
     "options": {"A": "Decision trees", "B": "k-NN and gradient-descent-based models", "C": "Random forests only", "D": "It's never necessary"},
     "correct_option": "B", "difficulty": 2, "explanation": "Distance-based methods (k-NN) and gradient-based optimization are sensitive to feature scale; tree-based models generally aren't."},
    {"concept_slug": "ml-preprocessing", "text": "Replacing missing values with the column's mean or median is called:",
     "options": {"A": "Normalization", "B": "Imputation", "C": "Regularization", "D": "Encoding"}, "correct_option": "B",
     "difficulty": 2, "explanation": "Imputation fills in missing data using a statistic (or model) rather than dropping the row entirely."},

    {"concept_slug": "ml-feature-engineering", "text": "Creating a new feature by combining or transforming existing ones is an example of:",
     "options": {"A": "Model evaluation", "B": "Feature engineering", "C": "Cross-validation", "D": "Regularization"}, "correct_option": "B",
     "difficulty": 2, "explanation": "Feature engineering is the process of designing input features (e.g. ratios, date parts) that help a model learn better."},
    {"concept_slug": "ml-feature-engineering", "text": "One-hot encoding is typically used to represent:",
     "options": {"A": "Continuous numeric variables", "B": "Categorical variables", "C": "Missing values", "D": "The target variable in regression"},
     "correct_option": "B", "difficulty": 2, "explanation": "One-hot encoding turns a categorical variable into multiple binary columns, one per category, suitable for models expecting numeric input."},

    {"concept_slug": "ml-train-test-split", "text": "Evaluating a model on the exact same data it was trained on gives:",
     "options": {"A": "An unbiased estimate of real-world performance", "B": "An overly optimistic performance estimate", "C": "No usable information at all", "D": "A guaranteed underestimate"},
     "correct_option": "B", "difficulty": 2, "explanation": "The model has already seen (and partly memorized) that data, so its performance there overstates how it'll do on new data."},
    {"concept_slug": "ml-train-test-split", "text": "A commonly used train/test split ratio for a moderately sized dataset is:",
     "options": {"A": "50/50 always required", "B": "80/20", "C": "99/1 always required", "D": "There is no such thing as a split ratio"},
     "correct_option": "B", "difficulty": 1, "explanation": "80/20 (or similar, like 70/30) is a common default, though the right ratio depends on dataset size."},

    {"concept_slug": "ml-overfitting", "text": "A model that performs very well on training data but poorly on new/test data is:",
     "options": {"A": "Underfitting", "B": "Overfitting", "C": "Perfectly generalized", "D": "Undertrained"},
     "correct_option": "B", "difficulty": 2, "explanation": "Overfitting means the model learned noise/specifics of the training set rather than the general underlying pattern."},
    {"concept_slug": "ml-overfitting", "text": "Which of the following is a common technique to reduce overfitting?",
     "options": {"A": "Removing all regularization", "B": "Adding regularization or gathering more training data", "C": "Training for as many epochs as possible with no limit", "D": "Using an even more complex model"},
     "correct_option": "B", "difficulty": 3, "explanation": "Regularization constrains model complexity, and more data reduces the chance of fitting to noise -- both fight overfitting."},
]
