"""sparkle multi-subject concepts

Revision ID: db0ba60b633e
Revises: e1cbdb6e08fb
Create Date: 2026-07-30 11:05:47.525755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0ba60b633e'
down_revision: Union[str, None] = 'e1cbdb6e08fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('subject', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_concepts_subject'), 'concepts', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concepts_subject'), table_name='concepts')
    op.drop_column('concepts', 'subject')
    # ### end Alembic commands ###
