"""phase2-8 schema additions

Revision ID: e1cbdb6e08fb
Revises: 5a15e5e19522
Create Date: 2026-07-28 06:48:44.562648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1cbdb6e08fb'
down_revision: Union[str, None] = '5a15e5e19522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_messages_id'), 'tutor_messages', ['id'], unique=False)
    op.add_column('concept_masteries', sa.Column('hidden_risk', sa.Boolean(), nullable=False))
    op.add_column('questions', sa.Column('secondary_concept_ids', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'secondary_concept_ids')
    op.drop_column('concept_masteries', 'hidden_risk')
    op.drop_index(op.f('ix_tutor_messages_id'), table_name='tutor_messages')
    op.drop_table('tutor_messages')
    # ### end Alembic commands ###
